### PR TITLE
Allow tomcat server to change java home

### LINKED ISSUE #53: "vm.install.path" Server Parameter doesn't work
[redhat-developer/vscode-java](https://github.com/redhat-developer/vscode-java) updated and now requires JDK 11+ which creates an issue with the java.home setting. For example, I am working with Tomcat 8.5 and need to be able to run it with JDK 8, but since it utilizes java.home the server will always start with JDK 11+. I was looking at [redhat-developer/vscode-rsp-ui](https://github.com/redhat-developer/vscode-rsp-ui#global-server-parameters) and saw that they include a server parameter vm.install.path that allows for us to set the path for java home, but it seems that this extension does not utilize this parameter as even after setting the parameter the server still utilizes the JDK path set by java.home.

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #53

### CODE REVIEW

**Comment by jeffmaury** [comment]
I have a concern with this PR because it seems to fix the issue for Tomcat only but I think other implementations (Jetty, Glassfish, Karaf) are also concerned. WDYT ?

**Comment by lstocchi** [comment]
The idea was to do that at first (add the feature to all server types) but then i thought that it would be better to only fix the urgent issues asked by users and leave the rest to Rob when he comes back. The first problem is that i don't know if it makes sense to add the feature to all of them (for instance, i don't know anything about Jetty and Karaf, maybe they have a configuration file users can edit to change the java used??), secondly i wanted to speed up with the release. If we only cover tomcat we need to test less stuff.

**Comment by jeffmaury** [comment]
I understand but then we should have at least one issue created for checking the other implementations in the future

**Comment by odockal** [comment]
@jeffmaury This #55 issue should cover fix for others where necessary.

**Comment by odockal** [comment]
@lstochi Anyway, I have merged rsp-server PR, we should first release rsp server and then update targetplatform dependency to released server version to get changes here, right?

**Comment by lstocchi** [comment]
@odockal yes, before releasing the community rsp we need to update targetplatform with the new rsp-server

**Comment by robstryker2** [comment]
I don't actually understand what was done in this issue. The commit is thin, the issue is still open, and I'm confused.  @lstocchi ?

**Comment by lstocchi** [comment]
This is the second part of this PR https://github.com/redhat-developer/rsp-server/pull/592 to extend the `vm.install.path` to the generic servers (in this specific case, tomcat). At first we couldn't merge it because we didn't have rights in this repo, then when Jeff came back from PTO, I got busy with other stuff and i forgot it sorry

**Comment by robstryker** [comment]
This patch really doesn't seem like it does anything at all. All it does is make Tomcat implement a different interface with no methods, ie, gaining it access to different constants. BUT, the only constant being changed (SERVER_HOME_DIR) has the exact same value in both classes and thus it appears to be no change at all?

**Comment by robstryker** [comment]
Confirmed that this patch is unnecessary. Overriding the Vm already works for tomcat, felix, karaf, etc based on the changes present in the generic bundle.

**Pull request closed without merging**
